SYS@XEPDB1 으로 접속해서

CREATE USER 아이디 IDENTIFIED BY 비밀번호;
GRANT CONNECT, RESOURCE TO 아이디;
ALTER USER 아이디 QUOTA UNLIMITED ON USERS;

CREATE USER KHC95 IDENTIFIED BY java;
GRANT CONNECT, RESOURCE TO KHC95;
ALTER USER KHC95 QUOTA UNLIMITED ON USERS;


-- HR.EMPLOYESS 테이블에 EMP_NAME 초기값이 NULL로 돼있음
-- UPDATE 시켜야됨
UPDATE HR.EMPLOYEES
SET EMP_NAME = FIRST_NAME || ' ' || LAST_NAME;

-- 조회하고 싶은 계정에서 다른 계정 테이블을 조회할때 00942에러 발생시 GRANT를 해줘야됨
-- 해당 계정의 테이블 하나씩 해줘야된다.
GRANT SELECT ON khc95.BUYER TO HR
GRANT SELECT ON khc95.BUYPROD TO HR
GRANT SELECT ON khc95.CART TO HR
GRANT SELECT ON khc95.LPROD TO HR
GRANT SELECT ON khc95.MEMBER TO HR
GRANT SELECT ON khc95.PROD TO HR
GRANT SELECT ON khc95.REMAIN TO HR

GRANT UPDATE ON HR.COUNTRIES TO KHC95;
GRANT UPDATE ON HR.DEPARTMENTS TO KHC95;
GRANT UPDATE ON HR.EMPLOYEES TO KHC95;
GRANT UPDATE ON HR.JOB_HISTORY TO KHC95;
GRANT UPDATE ON HR.JOBS TO KHC95;
GRANT UPDATE ON HR.LOCATIONS TO KHC95;
GRANT UPDATE ON HR.FRGIONS TO KHC95;