2025-1226-01) PL/SQL

DECLARE
    L_PROD_ID PROD.PROD_ID%TYPE;  --상품코드
    L_PROD_NAME  PROD.PROD_NAME%TYPE;  --상품명
    L_AMT NUMBER:=0; --매입금액
    
    CURSOR CUR_BUYPROD_01 IS
      SELECT A.PROD_ID, B.PROD_NAME, SUM(A.BUY_QTY*B.PROD_COST)
        FROM BUYPROD A
       INNER JOIN PROD B ON(A.PROD_ID=B.PROD_ID)
       WHERE A.BUY_DATE BETWEEN TO_DATE('20200501') AND TO_DATE('20200531')
       GROUP BY A.PROD_ID, B.PROD_NAME
      HAVING SUM(A.BUY_QTY*B.PROD_COST)>=5000000;
  BEGIN
    OPEN CUR_BUYPROD_01;
    LOOP
      FETCH CUR_BUYPROD_01  INTO L_PROD_ID,L_PROD_NAME,L_AMT;
      EXIT WHEN CUR_BUYPROD_01%NOTFOUND;
      DBMS_OUTPUT.PUT_LINE('상품코드 : '||L_PROD_ID);
      DBMS_OUTPUT.PUT_LINE('상품명 : '||L_PROD_NAME);
      DBMS_OUTPUT.PUT_LINE('매입금액 : '||TO_CHAR(L_AMT,'99,999,999'));
      DBMS_OUTPUT.PUT_LINE('-----------------------');
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('처리건수 : '||CUR_BUYPROD_01%ROWCOUNT);
      
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('예외발생 : '||SQLERRM);
  END;